# Generated by Django 6.0 on 2025-12-17 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('next_project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('image_name', models.CharField(blank=True, default='default.jpg', help_text="Enter the image filename (eg 'An image of...)", max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Contact', 'verbose_name_plural': 'Contact'},
        ),
        migrations.AlterModelOptions(
            name='register',
            options={'verbose_name': 'Register', 'verbose_name_plural': 'Register'},
        ),
        migrations.CreateModel(
            name='CardTextTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('es', 'Spanish')], max_length=5)),
                ('content', models.TextField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='next_project.cardtext')),
            ],
        ),
    ]
