# Generated by Django 6.0 on 2026-01-08 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('next_project', '0004_commentreaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
